select * from product_donation_details;
select * from product_donation;
select * from financial_contribution;
select * from contribution;
select * from community_company_product;
select * from product;
select * from community_company;
select * from donor;
select * from person;
